//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHGSZD.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHGSZD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _15_20蓝色报警框闪烁 {
            get {
                object obj = ResourceManager.GetObject("15-20蓝色报警框闪烁", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _15_20蓝色报警状态 {
            get {
                object obj = ResourceManager.GetObject("15-20蓝色报警状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20_25黄色报警框闪烁 {
            get {
                object obj = ResourceManager.GetObject("20-25黄色报警框闪烁", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20_25黄色报警状态 {
            get {
                object obj = ResourceManager.GetObject("20-25黄色报警状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _25_30橙色报警框闪烁 {
            get {
                object obj = ResourceManager.GetObject("25-30橙色报警框闪烁", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _25_30橙色报警状态 {
            get {
                object obj = ResourceManager.GetObject("25-30橙色报警状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _30红色报警框闪烁 {
            get {
                object obj = ResourceManager.GetObject("30红色报警框闪烁", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _30红色报警状态 {
            get {
                object obj = ResourceManager.GetObject("30红色报警状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KTK {
            get {
                object obj = ResourceManager.GetObject("KTK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单电网断线 {
            get {
                object obj = ResourceManager.GetObject("单电网断线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单白线1 {
            get {
                object obj = ResourceManager.GetObject("单白线1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单红线1 {
            get {
                object obj = ResourceManager.GetObject("单红线1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单红线11 {
            get {
                object obj = ResourceManager.GetObject("单红线11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单绿线_短1 {
            get {
                object obj = ResourceManager.GetObject("单绿线 短1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单绿线长 {
            get {
                object obj = ResourceManager.GetObject("单绿线长", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单黄线 {
            get {
                object obj = ResourceManager.GetObject("单黄线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 单黄线1 {
            get {
                object obj = ResourceManager.GetObject("单黄线1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双电网断线 {
            get {
                object obj = ResourceManager.GetObject("双电网断线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双白线 {
            get {
                object obj = ResourceManager.GetObject("双白线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双红线 {
            get {
                object obj = ResourceManager.GetObject("双红线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双绿线_短 {
            get {
                object obj = ResourceManager.GetObject("双绿线 短", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双绿线_长 {
            get {
                object obj = ResourceManager.GetObject("双绿线 长", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图片6 {
            get {
                object obj = ResourceManager.GetObject("图片6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 地震报警 {
            get {
                object obj = ResourceManager.GetObject("地震报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 地震故障 {
            get {
                object obj = ResourceManager.GetObject("地震故障", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 地震正常 {
            get {
                object obj = ResourceManager.GetObject("地震正常", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物kuang {
            get {
                object obj = ResourceManager.GetObject("异物kuang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物按钮不可用 {
            get {
                object obj = ResourceManager.GetObject("异物按钮不可用", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物按钮可用 {
            get {
                object obj = ResourceManager.GetObject("异物按钮可用", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物按钮操作完成 {
            get {
                object obj = ResourceManager.GetObject("异物按钮操作完成", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物灰灯 {
            get {
                object obj = ResourceManager.GetObject("异物灰灯", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物红底 {
            get {
                object obj = ResourceManager.GetObject("异物红底", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物红灯 {
            get {
                object obj = ResourceManager.GetObject("异物红灯", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物绿灯 {
            get {
                object obj = ResourceManager.GetObject("异物绿灯", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物黄灯 {
            get {
                object obj = ResourceManager.GetObject("异物黄灯", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 异物黑底 {
            get {
                object obj = ResourceManager.GetObject("异物黑底", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 正常状态 {
            get {
                object obj = ResourceManager.GetObject("正常状态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 电网正常 {
            get {
                object obj = ResourceManager.GetObject("电网正常", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 电网灰色 {
            get {
                object obj = ResourceManager.GetObject("电网灰色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 电网闪烁 {
            get {
                object obj = ResourceManager.GetObject("电网闪烁", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 白桥 {
            get {
                object obj = ResourceManager.GetObject("白桥", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 白点 {
            get {
                object obj = ResourceManager.GetObject("白点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 监控单元失效 {
            get {
                object obj = ResourceManager.GetObject("监控单元失效", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 红电网 {
            get {
                object obj = ResourceManager.GetObject("红电网", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绿点 {
            get {
                object obj = ResourceManager.GetObject("绿点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绿电网 {
            get {
                object obj = ResourceManager.GetObject("绿电网", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 车站 {
            get {
                object obj = ResourceManager.GetObject("车站", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 车站1 {
            get {
                object obj = ResourceManager.GetObject("车站1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 车站2 {
            get {
                object obj = ResourceManager.GetObject("车站2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 雨1级报警 {
            get {
                object obj = ResourceManager.GetObject("雨1级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 雨2级报警 {
            get {
                object obj = ResourceManager.GetObject("雨2级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 雨正常 {
            get {
                object obj = ResourceManager.GetObject("雨正常", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风0级报警 {
            get {
                object obj = ResourceManager.GetObject("风0级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风1级报警 {
            get {
                object obj = ResourceManager.GetObject("风1级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风1级报警1 {
            get {
                object obj = ResourceManager.GetObject("风1级报警1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风2级报警 {
            get {
                object obj = ResourceManager.GetObject("风2级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风3级报警 {
            get {
                object obj = ResourceManager.GetObject("风3级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风4级报警 {
            get {
                object obj = ResourceManager.GetObject("风4级报警", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 黄电网 {
            get {
                object obj = ResourceManager.GetObject("黄电网", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 黑点 {
            get {
                object obj = ResourceManager.GetObject("黑点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
